# Generated by Django 4.2.11 on 2025-11-05 00:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemons'},
        ),
        migrations.CreateModel(
            name='PokemonSpecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specie', to='pokemons.pokemon')),
            ],
            options={
                'verbose_name': 'Pokemon Specie',
                'verbose_name_plural': 'Pokemon Species',
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='PokemonEvolutionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('specie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_chain', to='pokemons.pokemonspecie')),
            ],
            options={
                'verbose_name': 'Pokemon Evolution Chain',
                'verbose_name_plural': 'Pokemon Evolution Chains',
                'ordering': ['external_id'],
            },
        ),
    ]
