# Generated by Django 4.2.11 on 2025-11-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_alter_pokemon_options_pokemonspecie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonevolutionchain',
            name='pokemon',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evolution_chains', to='pokemons.pokemon'),
            preserve_default=False,
        ),
    ]
