# Generated by Django 4.2.11 on 2025-11-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_pokemonevolutionchain_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonevolutionchain',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemonevolutionchain',
            name='specie',
        ),
        migrations.AddField(
            model_name='pokemonevolutionchain',
            name='pokemons',
            field=models.ManyToManyField(blank=True, related_name='evolution_chains', to='pokemons.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemonevolutionchain',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='evolution_chains', to='pokemons.pokemonspecie'),
        ),
    ]
