# Generated by Django 4.2.11 on 2025-11-05 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemons', '0004_remove_pokemonevolutionchain_pokemon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritedPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_pokemons', to='pokemons.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_pokemons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorited Pokemon',
                'verbose_name_plural': 'Favorited Pokemons',
                'ordering': ['user', 'pokemon'],
            },
        ),
    ]
